### ISSUE TITLE
does not compile on ubuntu since version 18 due to libpng

### ISSUE THREAD

**Issue by gogo2464** [raphnet/gbcam2png#4]
in the latest version of ubuntu libpng has been updated. It now requires to add the argument -lpng at the end of the command `gcc`. I have already made a pull request here: https://github.com/raphnet/gbcam2png/pull/3 . Fell free to merge.

**Comment by raphnet** [comment]
I just pushed a fix, the argument order when linking was incorrect (libs should come last). Could you try?

**Comment by gogo2464** [comment]
yes I am going to. I am just disapointed. I hoped we will do everything on my PR.

**Comment by gogo2464** [comment]
But yes your fix works...

**Comment by raphnet** [comment]
I have removed all commits for you, the Makefile is back to its original broken state. Please send a pull request with the fix.

**Comment by gogo2464** [comment]
This pull request sounds perfect. I hope it will be the last. https://github.com/raphnet/gbcam2png/pull/6

**Comment by raphnet** [comment]
Merged, thanks!!
